[package]
name = "mandelbrot"
version = "0.1.0"
authors = ["thash <hash@hzl.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.1.27"
image = "0.23.12"
crossbeam-utils = "0.8.7"
